package cn.inrhor.imipetcore.common.hook.protocol.version

class EntityMap3: EntityMap() {

    /**
     * 1.19 ProtocolLib 实体类型 对应 实体序号
     *
     * https://wiki.vg/Entity_metadata#Mobs
     */
    private val entityMap3 = mapOf(
        "AXOLOTL" to 4,
        "BAT" to 5,
        "BEE" to 6,
        "BLAZE" to 7,
        "CAT" to 10,
        "CAVE_SPIDER" to 11,
        "CHICKEN" to 12,
        "COD" to 13,
        "COW" to 14,
        "CREEPER" to 15,
        "DOLPHIN" to 16,
        "DONKEY" to 17,
        "DROWNED" to 19,
        "ELDER_GUARDIAN" to 20,
        "ENDER_DRAGON" to 22,
        "ENDERMAN" to 23,
        "ENDERMITE" to 24,
        "EVOKER" to 25,
        "EVOKER_FANGS" to 26,
        "FOX" to 31,
        "FROG" to 32,
        "GHAST" to 33,
        "GIANT" to 34,
        "GLOW_SQUID" to 36,
        "GOAT" to 37,
        "GUARDIAN" to 38,
        "HOGLIN" to 39,
        "HORSE" to 40,
        "HUSK" to 41,
        "ILLUSIONER" to 42,
        "IRON_GOLEM" to 43,
        "LLAMA" to 49,
        "MAGMA_CUBE" to 51,
        "MULE" to 60,
        "MUSHROOM_COW" to 61,
        "OCELOT" to 62,
        "PANDA" to 64,
        "PARROT" to 65,
        "PHANTOM" to 66,
        "PIG" to 67,
        "PIGLIN" to 68,
        "PIGLIN_BRUTE" to 69,
        "PILLAGER" to 70,
        "POLAR_BEAR" to 71,
        "PUFFERFISH" to 73,
        "RABBIT" to 74,
        "RAVAGER" to 75,
        "SALMON" to 76,
        "SHEEP" to 77,
        "SHULKER" to 78,
        "SILVERFISH" to 80,
        "SKELETON" to 81,
        "SKELETON_HORSE" to 82,
        "SLIME" to 83,
        "SNOWMAN" to 85,
        "SPIDER" to 88,
        "SQUID" to 89,
        "STRAY" to 90,
        "STRIDER" to 91,
        "TADPOLE" to 92,
        "TRADER_LLAMA" to 98,
        "TROPICAL_FISH" to 99,
        "TURTLE" to 100,
        "VEX" to 101,
        "VILLAGER" to 102,
        "VINDICATOR" to 103,
        "WANDERING_TRADER" to 104,
        "WARDEN" to 105,
        "WITCH" to 106,
        "WITHER" to 107,
        "WITHER_SKELETON" to 108,
        "WOLF" to 110,
        "ZOGLIN" to 111,
        "ZOMBIE" to 112,
        "ZOMBIE_HORSE" to 113,
        "ZOMBIE_VILLAGER" to 114,
        "ZOMBIFIED_PIGLIN" to 115,
    )

    override fun getEntityId(entityType: String): Int {
        return entityMap3[entityType]?: 67
    }

}