package cn.inrhor.imipetcore.common.hook.protocol.version

class EntityMap2: EntityMap() {

    /**
     * 1.18.2 实体类型 对应 实体序号
     *
     * https://pokechu22.github.io/Burger/1.18.2.json
     */
    private val entityMap2 = mapOf(
        "AXOLOTL" to 3,
        "BAT" to 4,
        "BEE" to 5,
        "BLAZE" to 6,
        "BOAT" to 7,
        "CAT" to 8,
        "CAVE_SPIDER" to 9,
        "CHICKEN" to 10,
        "COD" to 11,
        "COW" to 12,
        "CREEPER" to 13,
        "DOLPHIN" to 14,
        "DONKEY" to 15,
        "DRAGON_FIREBALL" to 16,
        "DROWNED" to 17,
        "ELDER_GUARDIAN" to 18,
        "ENDER_DRAGON" to 20,
        "ENDERMAN" to 21,
        "ENDERMITE" to 22,
        "EVOKER" to 23,
        "EVOKER_FANGS" to 24,
        "FALLING_BLOCK" to 27,
        "FOX" to 29,
        "GHAST" to 30,
        "GIANT" to 31,
        "GLOW_SQUID" to 33,
        "GOAT" to 34,
        "GUARDIAN" to 35,
        "HOGLIN" to 36,
        "HORSE" to 37,
        "HUSK" to 38,
        "ILLUSIONER" to 39,
        "IRON_GOLEM" to 40,
        "LLAMA" to 46,
        "LLAMA_SPIT" to 47,
        "MAGMA_CUBE" to 48,
        "MUSHROOM_COW" to 58,
        "MULE" to 57,
        "OCELOT" to 59,
        "PANDA" to 61,
        "PARROT" to 62,
        "PHANTOM" to 63,
        "PIG" to 64,
        "PIGLIN" to 65,
        "PIGLIN_BRUTE" to 66,
        "PILLAGER" to 67,
        "POLAR_BEAR" to 68,
        "PUFFERFISH" to 70,
        "RABBIT" to 71,
        "RAVAGER" to 72,
        "SALMON" to 73,
        "SHEEP" to 74,
        "SHULKER" to 75,
        "SHULKER_BULLET" to 76,
        "SILVERFISH" to 78,
        "SKELETON" to 79,
        "SKELETON_HORSE" to 80,
        "SLIME" to 80,
        "SNOWMAN" to 82,
        "SPIDER" to 85,
        "SQUID" to 86,
        "STRAY" to 87,
        "STRIDER" to 88,
        "TRADER_LLAMA" to 94,
        "TRIDENT" to 93,
        "TROPICAL_FISH" to 95,
        "TURTLE" to 96,
        "VEX" to 97,
        "VILLAGER" to 98,
        "VINDICATOR" to 99,
        "WANDERING_TRADER" to 100,
        "WITCH" to 101,
        "WITHER" to 102,
        "WITHER_SKELETON" to 103,
        "WITHER_SKULL" to 104,
        "WOLF" to 105,
        "ZOGLIN" to 106,
        "ZOMBIE" to 107,
        "ZOMBIE_HORSE" to 108,
        "ZOMBIE_VILLAGER" to 109,
        "ZOMBIFIED_PIGLIN" to 110,
    )


    override fun getEntityId(entityType: String): Int {
        return entityMap2[entityType] ?: 64
    }

}